apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-recreate
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echo
      strategy: recreate
  template:
    metadata:
      labels:
        app: echo
        strategy: recreate
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo:0.2.3
        args:
          - "-text=Hello from v1"
          - "-listen=:80"
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet: { path: "/", port: 80 }
        livenessProbe:
          httpGet: { path: "/", port: 80 }
