apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
      version: blue
  template:
    metadata:
      labels:
        app: echo
        version: blue
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo:0.2.3
        args:
          - "-text=Hello from BLUE"
          - "-listen=:80"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet: { path: "/", port: 80 }
        livenessProbe:
          httpGet: { path: "/", port: 80 }
